# Generated by Django 6.0.5 on 2026-06-02 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procurement', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockBay',
            fields=[
                ('dock_id', models.AutoField(primary_key=True, serialize=False)),
                ('dock_name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Dock Bay',
                'verbose_name_plural': 'Dock Bays',
                'db_table': 'tbl_DockBays',
            },
        ),
        migrations.CreateModel(
            name='ElevatorSchedule',
            fields=[
                ('elevator_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('trip_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Elevator Schedule',
                'verbose_name_plural': 'Elevator Schedules',
                'db_table': 'tbl_ElevatorSchedule',
            },
        ),
        migrations.CreateModel(
            name='FreightElevator',
            fields=[
                ('elevator_id', models.AutoField(primary_key=True, serialize=False)),
                ('elevator_name', models.CharField(max_length=100, unique=True)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Freight Elevator',
                'verbose_name_plural': 'Freight Elevators',
                'db_table': 'tbl_FreightElevators',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=255)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('location_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'tbl_Locations',
            },
        ),
        migrations.CreateModel(
            name='FFEDelivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_status', models.CharField(blank=True, max_length=50, null=True)),
                ('required_on_site_date', models.DateField(blank=True, null=True)),
                ('total_installed_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('item', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.RESTRICT, to='procurement.item')),
                ('vendor', models.ForeignKey(db_column='VendorID', on_delete=django.db.models.deletion.RESTRICT, to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'FFE Delivery',
                'verbose_name_plural': 'FFE Deliveries',
                'db_table': 'tbl_FFE_Delivery',
            },
        ),
        migrations.CreateModel(
            name='FFEMove',
            fields=[
                ('move_id', models.AutoField(primary_key=True, serialize=False)),
                ('destination_room', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_floor', models.CharField(blank=True, max_length=50, null=True)),
                ('move_status', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery', models.ForeignKey(db_column='DeliveryID', on_delete=django.db.models.deletion.CASCADE, to='logistics.ffedelivery')),
                ('elevator_schedule', models.ForeignKey(db_column='ElevatorScheduleID', on_delete=django.db.models.deletion.CASCADE, to='logistics.elevatorschedule')),
            ],
            options={
                'verbose_name': 'FFE Move',
                'verbose_name_plural': 'FFE Moves',
                'db_table': 'tbl_FFE_Moves',
            },
        ),
        migrations.AddField(
            model_name='elevatorschedule',
            name='elevator',
            field=models.ForeignKey(db_column='ElevatorID', on_delete=django.db.models.deletion.RESTRICT, to='logistics.freightelevator'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Conflict', 'Conflict')], max_length=50, null=True)),
                ('priority', models.CharField(blank=True, choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50, null=True)),
                ('requires_elevator', models.BooleanField(default=False)),
                ('dock', models.ForeignKey(db_column='DockID', on_delete=django.db.models.deletion.RESTRICT, to='logistics.dockbay')),
                ('vendor', models.ForeignKey(db_column='VendorID', on_delete=django.db.models.deletion.RESTRICT, to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'db_table': 'tbl_Reservations',
            },
        ),
        migrations.AddField(
            model_name='ffedelivery',
            name='reservation',
            field=models.ForeignKey(db_column='ReservationID', on_delete=django.db.models.deletion.CASCADE, to='logistics.reservation'),
        ),
        migrations.AddField(
            model_name='elevatorschedule',
            name='reservation',
            field=models.ForeignKey(db_column='ReservationID', on_delete=django.db.models.deletion.CASCADE, to='logistics.reservation'),
        ),
    ]
