# Generated by Django 6.0.5 on 2026-06-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('manufacturer_id', models.AutoField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(max_length=255, unique=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'db_table': 'tbl_Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('nys_vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255, unique=True)),
                ('business_type', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('approved_status', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'tbl_Vendors',
            },
        ),
    ]
