# Generated by Django 6.0.5 on 2026-06-02 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('related_reservation', models.ForeignKey(blank=True, db_column='RelatedReservationID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.reservation')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'tbl_Alerts',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_required', models.IntegerField(blank=True, null=True)),
                ('forklift_required', models.BooleanField(default=False)),
                ('elevator_operator_required', models.BooleanField(default=False)),
                ('estimated_move_time', models.IntegerField(blank=True, null=True)),
                ('reservation', models.ForeignKey(db_column='ReservationID', on_delete=django.db.models.deletion.CASCADE, to='logistics.reservation')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'tbl_Resources',
            },
        ),
    ]
