# Generated by Django 6.0.5 on 2026-06-02 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contract_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('warranty', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('manufacturer', models.ForeignKey(db_column='ManufacturerID', on_delete=django.db.models.deletion.RESTRICT, to='vendors.manufacturer')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'tbl_Contracts',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('finish_size', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.RESTRICT, to='procurement.contract')),
                ('manufacturer', models.ForeignKey(db_column='ManufacturerID', on_delete=django.db.models.deletion.RESTRICT, to='vendors.manufacturer')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'tbl_Items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('fiscal_year', models.SmallIntegerField(blank=True, null=True)),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('item', models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.RESTRICT, to='procurement.item')),
                ('vendor', models.ForeignKey(db_column='VendorID', on_delete=django.db.models.deletion.RESTRICT, to='vendors.vendor')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'tbl_Orders',
            },
        ),
    ]
